### ISSUE TITLE
Podział zadań podczas pierwszego etapu prac programistycznych

### ISSUE THREAD

**Issue by mhamulak** [PizzaHub/PWZP#10]
Michał Pawlik:
- zakodowanie klasy "Zamowienie" oraz metod odpowiedzialnych za funkcjonalności związane z cennikiem z klasy "modelCennika",
- przeprowadzenie testów aplikacji.

Daniel Blokus:
- zakodowanie klasy "GUI" oraz metod odpowiedzialnych za wygląd cennika z klasy "modelCennika".

Mateusz Adamski:
- stworzenie brakujących elementów interfejsu graficznego,
- aktualizowanie dokumentacji projektowej,
- kontrolowanie, czy prace programistyczne postępują zgodnie z założeniami przyjętymi w dokumentacji projektowej.

Maciej Hamulak:
- rozstrzyganie sporów na lini programiści-dokumentalista, grafik
- podział zadań w zespole,
- ustalanie terminów zadań,
- kontrola postępu prac,
- odpowiedzialność za dotrzymanie terminów.

Planowany termin zakończenia tego etapu prac to 13.04.2015. W ramach powyższych zadań będą pojawiały się mniejsze zadania z konkretnymi terminami ich wykonania.

**Comment by danielblokus** [comment]
Przyjąłem
