### ISSUE TITLE
Diagram klas

### ISSUE THREAD

**Issue by mhamulak** [PizzaHub/PWZP#6]
Musimy przygotować diagram klas. Jako, że nie mamy w naszym zespole analityka, a nie chcę zrzucać tego zadania na kogoś, kto sobie z nim nie poradzi, musimy rozwiązać ten problem wspólnymi siłami. 
Macie czas do <b>poniedziałku (16.03.2015)</b>  na przemyślenie sprawy i przygotowanie swoich propozycji. W poniedziałek się spotkamy, ocenimy efekty pracy i stworzymy jedną wersję diagramu.
Nie chciałbym, żeby w poniedziałek okazało się, że ktoś w ogóle nie zainteresował się tematem. Jednak jeśli taka sytuacja będzie miała miejsce, potraktuję to jako <b>niedotrzymanie terminu powierzonego zadania.</b>
Proszę skontaktować się ze mną w sprawie <b>ustalenia godziny spotkania.</b> Jeśli nie otrzymam waszych propozycji, sam ją ustalę.

**Comment by MichalPawlik** [comment]
W poniedziałek to mogę od 16:00 do 18:00 bo mam przerwę w zajęciach. Ewentualnie w przerwach między zajęciami.

**Comment by mhamulak** [comment]
Ustalam godzinę spotkania na 16:00.
